In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the eaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the eaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
vocab_size = 10000

In [5]:
## One Hot Representation 
one_hot_repr = [one_hot(words,vocab_size) for words in sent]
one_hot_repr

[[3190, 5498, 3489, 8596],
 [3190, 5498, 3489, 2543],
 [3190, 5237, 3489, 2660],
 [7967, 6316, 6535, 8717, 1383],
 [7967, 6316, 6535, 8717, 6320],
 [3664, 3190, 7581, 3489, 9162],
 [1507, 7075, 4605, 8717]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3190 5498 3489 8596]
 [   0    0    0    0 3190 5498 3489 2543]
 [   0    0    0    0 3190 5237 3489 2660]
 [   0    0    0 7967 6316 6535 8717 1383]
 [   0    0    0 7967 6316 6535 8717 6320]
 [   0    0    0 3664 3190 7581 3489 9162]
 [   0    0    0    0 1507 7075 4605 8717]]


In [11]:
## Feature representation of words using Embedding layer

dim = 10

In [14]:
'''model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse') ---krish's version
'''

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(input_dim=vocab_size, output_dim=dim)
])

model.compile('adam', 'mse')

In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[[-8.33195448e-03,  3.09995152e-02,  3.43071483e-02,
          5.77379391e-03, -3.06679737e-02,  1.80725344e-02,
         -4.93979938e-02, -3.91266234e-02,  3.01063769e-02,
          1.92147493e-03],
        [-8.33195448e-03,  3.09995152e-02,  3.43071483e-02,
          5.77379391e-03, -3.06679737e-02,  1.80725344e-02,
         -4.93979938e-02, -3.91266234e-02,  3.01063769e-02,
          1.92147493e-03],
        [-8.33195448e-03,  3.09995152e-02,  3.43071483e-02,
          5.77379391e-03, -3.06679737e-02,  1.80725344e-02,
         -4.93979938e-02, -3.91266234e-02,  3.01063769e-02,
          1.92147493e-03],
        [-8.33195448e-03,  3.09995152e-02,  3.43071483e-02,
          5.77379391e-03, -3.06679737e-02,  1.80725344e-02,
         -4.93979938e-02, -3.91266234e-02,  3.01063769e-02,
          1.92147493e-03],
        [-4.50690761e-02,  4.96878363e-02, -1.28337629e-02,
          1.02776289e-03,  1.54347159e-02,  1.89065449e-02,
          3.53310592e-02, -3.85269523e-05,  3.172785

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3190, 5498, 3489, 8596], dtype=int32)

In [19]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[[-8.3319545e-03,  3.0999515e-02,  3.4307148e-02,  5.7737939e-03,
         -3.0667974e-02,  1.8072534e-02, -4.9397994e-02, -3.9126623e-02,
          3.0106377e-02,  1.9214749e-03],
        [-8.3319545e-03,  3.0999515e-02,  3.4307148e-02,  5.7737939e-03,
         -3.0667974e-02,  1.8072534e-02, -4.9397994e-02, -3.9126623e-02,
          3.0106377e-02,  1.9214749e-03],
        [-8.3319545e-03,  3.0999515e-02,  3.4307148e-02,  5.7737939e-03,
         -3.0667974e-02,  1.8072534e-02, -4.9397994e-02, -3.9126623e-02,
          3.0106377e-02,  1.9214749e-03],
        [-8.3319545e-03,  3.0999515e-02,  3.4307148e-02,  5.7737939e-03,
         -3.0667974e-02,  1.8072534e-02, -4.9397994e-02, -3.9126623e-02,
          3.0106377e-02,  1.9214749e-03],
        [-4.5069076e-02,  4.9687836e-02, -1.2833763e-02,  1.0277629e-03,
          1.5434716e-02,  1.8906545e-02,  3.5331059e-02, -3.8526952e-05,
          3.1727854e-02,  1.4518872e-03],
        [ 1.4884759e-02, -3.7976958e-02, -7.8076124e-04, -4.